---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.13.9

inputs:
  - name: dp-table-renderer

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-table-renderer/ci/scripts/build.sh
