---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9.4

inputs:
  - name: dp-table-renderer
    path: go/src/github.com/ONSdigital/dp-table-renderer

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-table-renderer/ci/scripts/build.sh
